// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeXZ-BGClvWEmQiW0CwCHxtftvgvXCv_w',
    appId: '1:466610445872:web:ed82199f65d8217b6097f5',
    messagingSenderId: '466610445872',
    projectId: 'sweetcakes-49453',
    authDomain: 'sweetcakes-49453.firebaseapp.com',
    storageBucket: 'sweetcakes-49453.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBjOt4fR6bQvDaqWn9Dfc3Bxnr_qyNuk',
    appId: '1:466610445872:android:cfa05aaa934701726097f5',
    messagingSenderId: '466610445872',
    projectId: 'sweetcakes-49453',
    storageBucket: 'sweetcakes-49453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaTR4bcDberYrZSHbcoy2H4cq13tnenjI',
    appId: '1:466610445872:ios:966e5c33ba3fb5936097f5',
    messagingSenderId: '466610445872',
    projectId: 'sweetcakes-49453',
    storageBucket: 'sweetcakes-49453.firebasestorage.app',
    iosBundleId: 'com.example.sweetcakes',
  );

}